### PR TITLE
CI: test with GAP 4.13; test with mininimal set of packages loaded

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
The failure is due to a genuine issue: you use `IsDigraph` in `gap/PolygonalComplexes/graphs.gd` unconditionally.

**Comment by MeikeWeiss** [comment]
We have added Digraphs to needed packages

**Comment by fingolfin** [comment]
OK that's a bit better but the tests still report issues when loading this package using the `OnlyNeeded` option (which suppresses loading of packages which are merely "suggested" but not "needed" in `PackageInfo.g`). 

First there are warnings:

```
Syntax warning: Unbound global variable in /tmp/gaproot/pkg/SimplicialSurfaces\
/gap/PolygonalComplexes/graphs.gi:444
        graph := NautyColoredGraph(edges, colours);
                 ^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /tmp/gaproot/pkg/SimplicialSurfaces\
/gap/PolygonalComplexes/graphs.gi:446
        perminv := CanonicalLabeling(graph);
                   ^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /tmp/gaproot/pkg/SimplicialSurfaces\
#I  SimplicialSurfaces: finish reading file 'read.g'
/unit_tests/test_main.g:58
    __SIMPLICIAL_Test_IncidenceNautyGraph();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /tmp/gaproot/pkg/SimplicialSurfaces\
/unit_tests/test_main.g:61
    __SIMPLICIAL_Test_EdgeNautyGraph();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /tmp/gaproot/pkg/SimplicialSurfaces\
/unit_tests/test_main.g:63
    __SIMPLICIAL_Test_FaceNautyGraph();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```


Then when running the tests an actual error:
```
Now running tests from tst/testall.g
Error, Variable: '__SIMPLICIAL_Test_IncidenceNautyGraph' must have an assigned value in
  __SIMPLICIAL_Test_IncidenceNautyGraph(  
 ); at /tmp/gaproot/pkg/SimplicialSurfaces/unit_tests/test_main.g:58 called from 
```

**Review by ReymondAkpanya — APPROVED** [review]

**Comment by fingolfin** [comment]
Note that there is a failure here in GAP 4.11. On the surface this might be due to the digraphs & grape versions back then being less compatible, so the order in which they are loaded matters...

One simple fix would  be to just require GAP >= 4.12 ?

**Pull request merged**
